### ISSUE TITLE
Validate Correctness of Generated Code

### ISSUE THREAD

**Issue by brettbuddin** [GeorgeMac/truce#13]
We have some golden files to assist in asserting the shape of the files we're generating, but not their functional correctness. Even minor changes to how the templates get generated leads to a tiny-loop of back-and-forth between the test and adjustments to tap things back into place.

Instead of chasing the rigidity of golden files, let's set up some projects in `testdata/` that implement a wide range of capabilities of the Truce specification. These projects will have a very simple `main` that tests things from the API contract provided by the generated code.

Once we've locked in the behavior, we really don't care so much about the shape of the generated code.

**Comment by GeorgeMac** [comment]
Finally closing all those old issues @brettbuddin
